project:
  type: website
  output-dir: docs

website:
  title: "GI Shiny python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/cybaea/GI-Shiny-python

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters: 
  - shinylive



